change_phase:
  name: Wachstumsphase ändern
  description: Wachstumsphase einer Pflanze ändern
  fields:
    entity_id:
      name: Pflanze
      description: Die Pflanze deren Phase geändert werden soll
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    new_stage:
      name: Neue Phase
      description: Die neue Wachstumsphase
      required: true
      selector:
        select:
          options:
            - label: Early Veg
              value: early_veg
            - label: Mid Veg
              value: mid_veg
            - label: Late Veg
              value: late_veg
            - label: Early Flower
              value: early_flower
            - label: Mid Flower
              value: mid_flower
            - label: Late Flower
              value: late_flower
            - label: Flushing
              value: flushing
            - label: Ernte/Fertig
              value: done
    notes:
      name: Notizen (optional)
      description: Notizen zum Phasenwechsel
      required: false
      example: "12/12 Zyklus gestartet"
      selector:
        text:

add_note:
  name: Notiz hinzufügen
  description: Notiz zu einer Pflanze hinzufügen
  fields:
    entity_id:
      name: Pflanze
      description: Die Pflanze zu der die Notiz gehört
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    note:
      name: Notiz
      description: Die Notiz die hinzugefügt werden soll
      required: true
      example: "LST angewendet"
      selector:
        text:

# ✅ NEW: Watering Services
water_plant:
  name: Pflanze gießen
  description: Pflanze mit angegebener Wassermenge gießen
  fields:
    entity_id:
      name: Pflanze
      description: Die zu gießende Pflanze (beliebiger Sensor der Pflanze)
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    volume_ml:
      name: Wassermenge (ml)
      description: Menge des Wassers in Millilitern
      required: true
      example: 2000
      selector:
        number:
          min: 1
          max: 10000
          step: 50
          unit_of_measurement: ml
    notes:
      name: Notizen (optional)
      description: Zusätzliche Notizen zum Gießvorgang
      required: false
      example: "Nach Düngung"
      selector:
        text:

water_plant_quick:
  name: Pflanze schnell gießen
  description: Pflanze mit Standard-Wassermenge gießen
  fields:
    entity_id:
      name: Pflanze
      description: Die zu gießende Pflanze (beliebiger Sensor der Pflanze)
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
