water_plant:
  name: Pflanze gießen
  description: Gießvorgang für eine Pflanze protokollieren
  fields:
    entity_id:
      name: Pflanze
      description: Die zu gießende Pflanze (beliebiger Sensor der Pflanze)
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    volume:
      name: Volumen (ml)
      description: Menge des Wassers in Millilitern
      required: true
      example: 500
      selector:
        number:
          min: 1
          max: 10000
          step: 1
          unit_of_measurement: ml
    ec:
      name: EC-Wert (optional)
      description: EC-Wert der Nährlösung in mS/cm
      required: false
      example: 1.8
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: mS/cm
    ph:
      name: pH-Wert (optional)
      description: pH-Wert der Nährlösung
      required: false
      example: 6.2
      selector:
        number:
          min: 4.0
          max: 8.0
          step: 0.1
          unit_of_measurement: pH
    notes:
      name: Notizen (optional)
      description: Zusätzliche Notizen zum Gießvorgang
      required: false
      example: "Nach Düngung"
      selector:
        text:

fertilize_plant:
  name: Pflanze düngen
  description: Düngung für eine Pflanze protokollieren
  fields:
    entity_id:
      name: Pflanze
      description: Die zu düngende Pflanze (beliebiger Sensor der Pflanze)
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    fertilizer:
      name: Dünger
      description: Name/Art des verwendeten Düngers
      required: true
      example: "BioBizz Grow"
      selector:
        text:
    ec:
      name: EC-Wert (optional)
      description: EC-Wert der Düngerlösung in mS/cm
      required: false
      example: 2.2
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: mS/cm
    ph:
      name: pH-Wert (optional)
      description: pH-Wert der Düngerlösung
      required: false
      example: 6.0
      selector:
        number:
          min: 4.0
          max: 8.0
          step: 0.1
          unit_of_measurement: pH
    notes:
      name: Notizen (optional)
      description: Zusätzliche Notizen zur Düngung
      required: false
      example: "Erste Blütendüngung"
      selector:
        text:

change_phase:
  name: Wachstumsphase ändern
  description: Wachstumsphase einer Pflanze ändern
  fields:
    entity_id:
      name: Pflanze
      description: Die Pflanze deren Phase geändert werden soll
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    new_stage:
      name: Neue Phase
      description: Die neue Wachstumsphase
      required: true
      selector:
        select:
          options:
            - label: Keimling
              value: seedling
            - label: Vegetativ
              value: vegetative
            - label: Blüte
              value: flowering
            - label: Ernte
              value: harvest
    notes:
      name: Notizen (optional)
      description: Notizen zum Phasenwechsel
      required: false
      example: "12/12 Zyklus gestartet"
      selector:
        text:

add_note:
  name: Notiz hinzufügen
  description: Notiz zu einer Pflanze hinzufügen
  fields:
    entity_id:
      name: Pflanze
      description: Die Pflanze zu der die Notiz gehört
      required: true
      selector:
        entity:
          domain: sensor
          integration: growflow
    note:
      name: Notiz
      description: Die Notiz die hinzugefügt werden soll
      required: true
      example: "LST angewendet"
      selector:
        text:
